name: Deploy on PR

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessario per la cronologia completa
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Push Force
        shell: pwsh
        run: |
          git fetch origin

          $mergeCommit = git log --oneline --merges --first-parent ${{ github.event.pull_request.head.ref }} --format="%H" | Select-Object -First 1
          $headCommit = git rev-parse ${{ github.event.pull_request.head.ref }}

          if ($mergeCommit) {
            Write-Host "Commit di merge trovato."
            if ($mergeCommit -eq $headCommit){
              Write-Host "Il commit di merge trovato è lo stesso della testa di ${{ github.event.pull_request.head.ref }}."
              Write-Host "Eseguo il push force..."
              git reset --hard origin/${{ github.event.pull_request.head.ref }}~  # Ripristina lo stato originale di A senza il merge commit
              git push --force origin ${{ github.event.pull_request.head.ref }}  # Forza il push per aggiornare A
              Write-Host "Push Force avvenuto correttamente."
            }else {
              Write-Host "Qualcosa è andato storto in quanto il workflow di prima doveva bloccare questa casistica."
              exit -1
            }
          }else{
            Write-Host "Nessun commit di merge rilevato. Proseguo tranquillamente."
          }
          