name: Deploy on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev

jobs:
  deploy:
    if: github.event.pull_request.base.ref == 'A' && github.event.pull_request.head.ref == 'B'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: echo "Deploying because PR from B to A was created or updated"

      - name: Run deployment script
        run: |
          echo "Starting deployment..."
          # Qui puoi aggiungere i tuoi comandi di deploy
